package main

type Sumifier interface {
	Add(a, b int32) int32
}

type Sumer struct {
	id int32
}

func (s Sumer) Add(a, b int32) int32 {
	return a + b
}

func main() {
	adder := Sumer{id: 6754}
	m := Sumifier(adder)
	m.Add(10, 12)
}

// go tool compile -m escape.go

// escape.go:11:6: can inline Sumer.Add
// escape.go:15:6: can inline main
// escape.go:18:7: devirtualizing m.Add to Sumer
// escape.go:17:15: Sumifier(adder) does not escape
// <autogenerated>:1: inlining call to Sumer.Add
